modLoader="javafml"
loaderVersion="[39,)" 
license="MIT"

[[mods]]
modId="lolenderite"
version="1.3.2-1.18.1"
displayName="Enderite"
logoFile="enderite_logo.png"
displayURL="https://www.youtube.com/channel/UCRW9cQ_rbr1K30obCA4oHUQ"
updateJSONURS="https://github.com/LieOnLion"
authors="LieOnLion"
description='''
Adds Enderite to the Game
'''